### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by taiti101112** [taiti101112/portfolio#18]
### 実装予定の機能
* ショップの作成機能
* ショップの削除機能
* ショップの閲覧機能

### 必要なページ
* ショップ一覧
* ショップ詳細
* トップページ(管理)
* ショップ新規作成(管理)
* ショップ一覧(管理)

**Comment by taiti101112** [comment]
issueベースの開発が完了しましたのでご確認のほどよろしくお願い致します。

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。
