### ISSUE TITLE
"MVPリリース"レビュー依頼

### ISSUE THREAD

**Issue by taiti101112** [taiti101112/portfolio#28]
### アプリ名：tcg-place  
https://tcgplace-9f88c4df2f96.herokuapp.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
* 会員登録
* ログイン
* パスワード変更
* メールアドレス変更
* ショップ一覧
* ショップ詳細
* ショップ検索(店名・取り扱いタイトル)

### 追加した機能
* ショップ作成
* ショップ削除
* ショップ編集

### 作らなかった機能
* 会員登録
* ログイン
* パスワード変更
* メールアドレス変更
* ショップ検索(店名・取り扱いタイトル)

### 一覧画面(管理ページ)
[![Image from Gyazo](https://i.gyazo.com/150d2c06f63658685ec51c52f6b64fd9.png)](https://gyazo.com/150d2c06f63658685ec51c52f6b64fd9)

### 新規作成画面(管理ページ)
[![Image from Gyazo](https://i.gyazo.com/e15f8106e53aafa6bae98a7bfb184c68.png)](https://gyazo.com/e15f8106e53aafa6bae98a7bfb184c68)

**Comment by taiti101112** [comment]
MVPリリースが完了しましたのでご確認のほどよろしくお願い致します。

**Comment by kenchasonakai** [comment]
ショップ作成ページがどこから行けばいいかわからなかったので教えていただけますでしょうか？
また、ショップ削除・ショップ編集機能も見当たりませんでした

ショップ一覧
ショップ詳細

**Comment by taiti101112** [comment]
ご確認いただきありがとうございます。
管理画面へのリンクは以下となります。
また、ショップの作成・削除・編集は管理者のみが行うことを想定しており、一般ユーザーの場合は詳細ページのみ閲覧できるようにしております。
お手数をおかけいたしますが再度レビューのほどよろしくお願い致します。

https://tcgplace-9f88c4df2f96.herokuapp.com/admin/shops

**Comment by Tsuchiya2** [comment]
ショップの検索機能はMVPに含めないと記載されていますが、なぜそうされたのかお聞きしても良いでしょうか。

意図：READMEを拝見すると「自分の目的に合ったカードショップを探すのに特化したサービス」「このサービスの差別化ポイントはこのサービス1つで自分の目当てのカードショップを検索できるところ」など、検索がキーになっていそうなため、そのキーポイントを外した理由をお聞きしたいです。（サービスを検証できる状態であるかも合わせてお聞きしたいです）

**Comment by taiti101112** [comment]
ショップの検索機能をMVPに含めなかったのはユーザーがショップ情報を閲覧できることでサービスが成立していると感じたからです。
ですがご指摘いただいたとおり、目的のショップを簡単に探せることをこのサービスの売りにしているのでREADMEに記載しているようにショップ名と取り扱いタイトルでの検索機能を実装して再度提出させていただきたいと思います。

**Comment by taiti101112** [comment]
## 各種情報
### アプリ名：tcg-place  
一般ユーザー
https://tcgplace-9f88c4df2f96.herokuapp.com/

管理ユーザー
https://tcgplace-9f88c4df2f96.herokuapp.com/admin/shops


## READMEレビュー時にMVPリリース時点で実装予定だった機能
* 会員登録
* ログイン
* パスワード変更
* メールアドレス変更
* ショップ一覧
* ショップ詳細
* ショップ検索(店名・取り扱いタイトル)


## READMEレビュー時から変更した機能

### 追加した機能
* ショップ作成
* ショップ削除
* ショップ編集

### 作らなかった機能
* 会員登録
* ログイン
* パスワード変更
* メールアドレス変更

## サービスイメージがわかるようなスクリーンショット等
### ショップ名での検索
[![Image from Gyazo](https://i.gyazo.com/e36fea9968be638ae1b13ad1effe808a.png)](https://gyazo.com/e36fea9968be638ae1b13ad1effe808a)

### タグでの検索
[![Image from Gyazo](https://i.gyazo.com/a893d818cb86a8962319ac32c176ce28.png)](https://gyazo.com/a893d818cb86a8962319ac32c176ce28)

**Comment by taiti101112** [comment]
お疲れ様です。
追加の実装が完了しましたのでご確認のほどよろしくお願いいたします。

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです！
引き続き本リリースに向けて開発頑張ってください。
